### PR TITLE
minor changes in `README`

### PR DESCRIPTION
**Pull request by 27Saumya**
• Change colour of license to blue because yellow is very shity lmao
• Grammar change

### CODE REVIEW

**Comment by nexxeln** [comment]
"fully" makes more sense to me, as for linting, markdown is whitespace collapsing so it doesn't matter lol.

**Comment by kekda-py** [comment]
I think it looks much better with cake cutter's yellow theme

**Comment by 27Saumya** [comment]
> 

But that colour looks like shit tbh

**Comment by 27Saumya** [comment]
> "fully" makes more sense to me, as for linting, markdown is whitespace collapsing so it doesn't matter lol.

Ik it does but it's kinda grammaticaly wrong tbh

**Comment by nexxeln** [comment]
are we really discussing color of badges here now?

> Ik it does but it's kinda grammaticaly wrong tbh
idk how's its grammatically wrong please explain

**Comment by kekda-py** [comment]
> > 
> 
> But that colour looks like shit tbh

did u understand what i said it looks good with the theme

**Comment by kekda-py** [comment]
very smol unnecessary pr

**Pull request closed without merging**
